title: My Personal Website
email: nautiyalanimesh.gmail.com
description: >-
  My journey through music, exercise, coding, and more.
baseurl: ""
url: "https://animeshn.github.io"
theme: jekyll-theme-tactile

# Build settings
markdown: kramdown

# Collections
collections:
  posts:
    output: true
