title: My Personal Website
email: your-email@example.com
description: >-
  My journey through music, exercise, coding, and more.
baseurl: ""
url: "https://your-username.github.io"
theme: jekyll-theme-tactile

# Build settings
markdown: kramdown

# Collections
collections:
  posts:
    output: true
