title: "Animesh Nautiyal"
email: "nautiyalanimesh@gmail.com"
description: "Personal site to document learning, projects, and progress — music, exercise, coding, climate, and more."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://animeshn.github.io" # replace with your GitHub Pages URL
# Use the Minimal Mistakes remote theme (works with GitHub Pages)
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author info (used by theme)
author:
  name: "Animesh Nautiyal"
  email: "nautiyalanimesh@gmail.com"
  bio: "MTech (Technology & Development) student at CTARA, IIT Bombay. Interested in health informatics, geospatial data, D3.js visualizations, flute practice, fitness, languages, and writing tutorials."

# Navigation (you can add categories to the menu manually if you want)
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Categories"
    url: "/categories/"

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "Animesh Nautiyal"

markdown: kramdown
highlighter: rouge
